# Generated by Django 5.2.6 on 2025-11-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShootingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название съемки')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('duration', models.CharField(max_length=100, verbose_name='Продолжительность')),
                ('includes', models.TextField(verbose_name='Что входит')),
            ],
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
