# Generated by Django 5.2.6 on 2025-11-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_shootingtype_delete_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='shootingtype',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на фото'),
        ),
    ]
